Refactor code, as to be consistent with standard C# formatting
equinor/ms-continuus pull request #10
Opened 2021-01-28 14:50 UTC by sindre-nistad

* Uses C#'s naming convention
* Used Rider's IntelliSence to refactor code as to be simpler, and (mostly) less verbose

2021-01-28 15:45 UTC, soofstad requested changes
A bit much "var"?

Must be tested thoroughly before merging

2021-01-28 15:45 UTC, soofstad commented on src/Utility.cs
> +            ;
?

2021-02-01 12:16 UTC, sindre-nistad commented on src/Utility.cs
> +            ;
Fixed

2021-02-03 09:11 UTC, soofstad approved these changes

2021-02-03 09:12 UTC, merged